version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast_epost_3_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./bin/dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app:cached

  worker:
    build: .
    command: bin/jobs
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app:cached

volumes:
  db_data:
