name: Setup Rails environment
description: Checkout repository, install optional apt packages, and configure Ruby with Bundler cache.

inputs:
  apt-packages:
    description: Space-separated apt packages to install.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install apt packages
      if: ${{ inputs.apt-packages != '' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y ${{ inputs.apt-packages }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
